version: '3.1'

services:
  node-app:
    build: .
    image: node-app
    command: tail -f /dev/null
    environment:
      MONGODB_URL: mongodb://wassali:pass@mongo:27017/
      MONGO_DATABASE: wassalidb
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/node-app
      - node_modules:/usr/src/node-app/node_modules
    networks:
      - node-network

  mongo:
    image: mongo:4.2.1-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: wassali
      MONGO_INITDB_ROOT_PASSWORD: pass

    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: wassali
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://wassali:pass@mongo:27017/
    networks:
      - node-network

volumes:
  dbdata:
  node_modules:

networks:
  node-network:
    driver: bridge
